---
language: ruby
rvm:
  - 2.2.5
before_install:
  - gem update --system
  - gem install bundler

before_script:
  - cp config/database.travis config/database.yml
  - bundle exec rake bootstrap

services:
  - mysql
