# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  encoding: utf8
  database: lvee_development
  pool: 5
  username: root
  password: Password
  host: localhost
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2 #jdbcmysql
  encoding: utf8
  database: lvee_test
  pool: 5
  username: root
  password: Password
  host: localhost
  socket: /var/lib/mysql/mysql.sock
production:
  adapter: mysql2
  encoding: utf8
  database: lvee_development
  pool: 5
  username: root
  password: p@ssw0rd
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

