development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  database: lvee_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  database: lvee_development

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  database: lvee_development
